# 在这里配置 权限服务 所有环境都能使用的配置
pinda:
  mysql:
    database: pd_sms
  swagger:
    enabled: true
    docket:
      sms:
        title: 短信发送服务
        base-package: com.itheima.sms.controller
  sms: 
    messageErrorNum: 3
    configLevelFailNum: 10
    configBuildScale: 0.75
    
authentication:
  user:
    header-name: token
    expire: 43200               # 外部token有效期为12小时
    pri-key: client/pri.key    # 加密
    pub-key: client/pub.key    # 解密
server:
  port: 8772

spring:
  cache:
    type: REDIS
  redis:
    database: 1 # Redis数据库索引（默认为0）
    #host: 192.168.0.201 # Redis服务器地址
    #port: 7001 # Redis服务器连接端口
    password: 123456 #czbk@redis@123456
    timeout: 10000ms # 连接超时时间（毫秒）默认是2000ms
    lettuce:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 3 # 连接池中的最小空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
    sentinel:
      master: mymaster
      nodes: #哨兵地址列表，多个以,分割
        - 52.83.92.196:26380
        - 52.83.92.196:26381
        - 52.83.92.196:26382 
    queue:
      pop:
        timeout: 8000 #消息队列等待时间 不能超过链接的超时时间